apiVersion: migrations.kubevirt.io/v1alpha1
kind: MigController
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-migration-operator
    app.kubernetes.io/managed-by: kustomize
  name: migcontroller-sample
spec:
  imagePullPolicy: Always
  infra:
    nodeSelector:
      kubernetes.io/arch: amd64
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/worker
      operator: Exists
